apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  # TODO: Set the number of replicas (use 1 for database)
  replicas: 1
  selector:
    matchLabels:
      # TODO: Define selector labels
      app: mysql
  template:
    metadata:
      labels:
        # TODO: Define pod labels (must match selector above)
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          # TODO: Configure MySQL environment variables
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
            - name: MYSQL_DATABASE
              value: "wordpress"
          ports:
            # TODO: Define the MySQL container port (MySQL uses 3306)
            - containerPort: 3306