apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  selector:
    # TODO: Define selector to match WordPress deployment (must match deployment labels)
    app: wordpress
  ports:
    # TODO: Configure WordPress service ports
    - protocol: TCP
      port: 80      # Service port (HTTP uses 80)
      targetPort: 80 # WordPress container port (80)
      nodePort: 30081  # External port for browser access (30000-32767)
  # TODO: Define service type for external access (use NodePort)
  type: NodePort