apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80      # Service port (HTTP uses 80)
      targetPort: 80 # WordPress container port (80)
      nodePort: 30081  # External port for browser access (30000-32767)
  type: NodePort