apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    app: webapp
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP   # Protocol type (TCP for HTTP traffic)
      port: 80       # Port exposed by the service (try 80)
      targetPort: 80 # Port on the container (nginx uses 80)
      nodePort: 30080   # External port on node (use 30080 or similar)


