services:
  app:
    build: ../.
    volumes:
      - ../:/app
    environment:
      - FLASK_DEBUG=1
      - PYTHONPATH=/app
    command: python -m debugpy --listen 0.0.0.0:5678 --wait-for-client app.py
    ports:
      # TODO: forward the ports required for App and Debugging
      - "5001:5000"   # acceso directo a Flask (salta nginx)
      - "5678:5678"   # debugpy (conecta tu IDE a localhost:5678)

  # Debug tools
  adminer:
    image: adminer
    ports:
      # TODO: Forward the port from docker to the host
      # Adminer uses port 8080 by default
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: database

  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      # TODO: Forward the redis-commander port 8081 to the host
      - "8081:8081"
    environment:
      REDIS_HOSTS: local:cache:6379
