version: "3.9"
services:
  # Application stack from previous section
  app:
    build: .
    environment:
     - DB_HOST=database
     - REDIS_HOST=cache
    depends_on:
     - database
     - cache
    networks:
      - app-network
      - monitoring

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: webapp
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    networks:
      - app-network

  cache:
    image: redis:7-alpine
    networks:
      - app-network

  # Monitoring services
  prometheus:
    image: prom/prometheus:latest
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monitoring

volumes:
  grafana_data:

networks:
  app-network:
  monitoring:
